### ISSUE TITLE
[1.19.2] Crashes on Startup on Quilt, possible incompatibility with Moonlight Lib

### ISSUE THREAD

**Issue by Hahahavana** [Tfarcenim/Daves-Potioneering#10]
Crash Report:
https://pastebin.com/e07AL7j1

**Comment by Hahahavana** [comment]
Update: startup crash is fixed in the more recent versions of Quilt, however this mod now causes a server crash (even on singleplayer) due to "Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_10545(String)" because the return value of "net.minecraft.class_1799.method_7969()" is null" when the gauntlet it in a player's inventory, which essentially bricks the world you crafted it in.

**Comment by Tfarcenim** [comment]
Post that log

**Comment by Hahahavana** [comment]
Sorry for the lack of response, my internet decided to give up the ghost for a week and it took a frustrating amount of time to get my ISP to fix it. Good news: the crash seems to be fixed on the most recent versions of the Quilt loader, again. I can't reproduce it after updating. Here's [that log](https://pastebin.com/4nn8D7vg) though, in case it helps. It was running on 0.18.1-beta 78 if I remember right.
