### ISSUE TITLE
[Issue] Problem loading mod?

### ISSUE THREAD

**Issue by Nekkok** [Tfarcenim/Daves-Potioneering#11]
Hi! I want to use this mod but I would like to configure its features for my modpack. The thing is... the mod is not appearing in ModMenu o_o And also, inside config folder, the file is empty. I'm using MC 1.19.2 with Fabric 0.14.13.

Im sending you the config and the log to see if you can tell what could be the possible error. Thank you! : )
[davespotioneering.json5](https://gist.github.com/Nekkok/e3fdd20890ee7a49a9092afb91097c23)
[latest.log](https://github.com/Tfarcenim/Daves-Potioneering/files/10582792/latest.log)

**Comment by Tfarcenim** [comment]
Mod version?

**Comment by Tfarcenim** [comment]
fixed
