### ISSUE TITLE
Unable to start game

### ISSUE THREAD

**Issue by Asveste** [Tfarcenim/Daves-Potioneering#12]
Basically what the title says.
Im using 1.16.5, Mod Version 0.5

Im not getting any crashlogs so here's the latest log:
https://gist.github.com/Asveste/0962ed306d8a745cb31f4f679a24e3c4

**Comment by Tfarcenim** [comment]
Can this be recreated in a clean instance

**Comment by Asveste** [comment]
Hey!
I tried to reproduce it right now and the newest mod release (Version 0.7) seems to have fixed the issue, as I was able to start the game without any problems.

**Comment by masonclomid** [comment]
Hello! I had the same problem in 1.16, crashing on startup even with the latest version of the mod:
![Dave-Crash](https://user-images.githubusercontent.com/101992860/224524880-36ceef07-94ad-4c6d-a8a6-d431d0927f74.png)
I only added geckolib and this mod, then this is part of the crash report:
https://gist.github.com/masonclomid/e9205a470fbe542bf40ebcc5da229878

**Comment by Tfarcenim** [comment]
> Optifine
So that's why, easy enough fix, stop using it
