### ISSUE TITLE
Incompatibility with FancyMenu and Optifine

### ISSUE THREAD

**Issue by JawboTau** [Tfarcenim/Daves-Potioneering#18]
After selectively disabling certain mods at a time, I found that the combination of the 2 mods (3 including libraries) below causes a crash, near the end of loading. I also tried adding OptiForge, in hopes that it would fix the crash, but it does not.
All mods are the latest version compatible with 1.16.5 as of this time.

### Game Log
https://gist.github.com/JawboTau/288c145f334ede8d33b7c163555195d4

### Mods
![image](https://user-images.githubusercontent.com/129625734/234158106-44d67114-0b78-4cac-bd4d-66b34309a042.png)

### Basic Info
 - OS: Windows 10
 - Forge Version 36.3.34
 - Minecraft Version 1.16.5

**Comment by Tfarcenim** [comment]
Remove Optifine, I'm not working around their bugs anymore.
