### ISSUE TITLE
Game crashes in 1.19.2 fabric

### ISSUE THREAD

**Issue by Ureiah** [Tfarcenim/Daves-Potioneering#21]
I created a custom resource for custom named elytras, but when i go to name them. The game crashes with this crash log.
[crash-2023-06-25_02.30.08-client.txt](https://github.com/SHsuperCM/CITResewn/files/11858987/crash-2023-06-25_02.30.08-client.txt)

Can i get some assistance? The issue is fixed when Dave's potioneering is disabled.

**Comment by SiverDX** [comment]
Could Imagine it being this

https://github.com/Tfarcenim/Daves-Potioneering/blob/aee63f3e77b7b9c9cfc1e01bcacdf1d080be1d05/src/main/java/tfar/davespotioneering/mixin/ItemOverrideListMixin.java#L21

**Comment by Ureiah** [comment]
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at net.minecraft.class_806.handler$cmj000$davespotioneering$validModel(class_806.java:521)
	on line 7 and 8?

This is my first time making a resource pack, so i have no idea what i did wrong. It does work fine without Dave's installed, but my players would unalive me if i removed it.

**Comment by Tfarcenim** [comment]
This one has to do with model overrides and I have no idea how to fix it, sorry

**Comment by Tfarcenim** [comment]
I found a workaround
