### ISSUE TITLE
[Fabric 1.20.1] Shift-Clicking bottles into slots causes an entire stack to be inserted

### ISSUE THREAD

**Issue by BlindTwig** [Tfarcenim/Daves-Potioneering#29]
As the title says, when shift-clicking bottles into slots for a brewing stand, either vanilla or modded ones, a whole stack will be inserted when it normally shouldn't. Because of this, if you continue to brew with the stacks in the slots they will be corrected after the brew is complete, causing you to permanently lose any extras, meaning 15 per slot in a stand. The compound stand doesn't lose them, but the limit seems to have been two potions per slot when adding them normally, so this likely isn't intended behavior.

A video demonstrating the issue:

https://github.com/Tfarcenim/Daves-Potioneering/assets/58229251/0a9bc939-e0fd-4544-9f77-9085614044b8

**Comment by Tfarcenim** [comment]
annoying, I fixed this for advanced brewing stand, working on a patch for regular brewing stand

**Comment by Tfarcenim** [comment]
fixed vanilla brewing stand
