### ISSUE TITLE
[Forge-1.18.2] Several Mods Crash When Installing Dave's Potioneering

### ISSUE THREAD

**Issue by PhweeDev** [Tfarcenim/Daves-Potioneering#3]
When downloading this mod and playing it, I noticed a lot of mods crashed on start up. Geckolib is installed, and I have the latest version of Forge. 

Crash Report: https://paste.gg/p/anonymous/9c06476a82094a97bfc71bff7c3bc54e

Latest.log: https://paste.gg/p/anonymous/7f42ec832c9e4a55949e464d3ad9d831

**Comment by Tfarcenim** [comment]
Does it load with nothing other than forge and geckolib installed?

**Comment by PhweeDev** [comment]
No.

Report: https://paste.gg/p/anonymous/5faaeb4ec15643c3bd6509e0185c5cc3
