### ISSUE TITLE
1.20.1 - config includes both coat_anything and coat_all

### ISSUE THREAD

**Issue by lynnpye** [Tfarcenim/Daves-Potioneering#30]
In tfar.davespotioneering.ModConfig.Server, the 'coat_all' variable is assigned twice, first as:
  coat_all = builder.define("coat_anything",false);
then as:
  coat_all = builder.comment("Allows all items to be coated").define("coat_all",false);

This causes the configuration to have a "coat_anything" value that can be assigned but will be ignored and has no translation key. Meanwhile the "coat_all" value is what is used.

It appears that the first assignment referencing "coat_anything" should be removed.

**Comment by Tfarcenim** [comment]
fixed 1.20.1-6
