### ISSUE TITLE
Recipes do not appear on creative menu or Just Enough Items

### ISSUE THREAD

**Issue by Jerhom3** [Tfarcenim/Daves-Potioneering#31]
Fabric Loader 0.14.25

Mod version fabric-1.20.1-1
JEI version Beta 15.2.0.27 for Fabric 1.20.1

![image](https://github.com/Tfarcenim/Daves-Potioneering/assets/152254711/1120505f-6207-4884-9ed0-dbd66fddeac6)

![image](https://github.com/Tfarcenim/Daves-Potioneering/assets/152254711/9e733818-9cc8-4a1a-9e16-c8c1005b36e3)

![image](https://github.com/Tfarcenim/Daves-Potioneering/assets/152254711/d3e4482e-e3c8-404e-aff8-b25045922c34)

**Comment by Tfarcenim** [comment]
fixed 1.20.1-6
