### ISSUE TITLE
[Bug] Crash when hopper tries transfering with brewing stand

### ISSUE THREAD

**Issue by Phoupraw** [Tfarcenim/Daves-Potioneering#32]
## Steps
1. Place a Compound Brewing Stand.
2. Place a hopper under it or pointing it.
3. Crash.
4. The world keeps crashing when entered.

## Versions
|MC|Forge|Daves-Potioneering|
|-|-|-|
|1.20.1|47.1.44|1.20.1-9|
## Logs
[crash-2024-01-29_12.59.47-server.txt](https://github.com/Tfarcenim/Daves-Potioneering/files/14079802/crash-2024-01-29_12.59.47-server.txt)
[latest.log](https://github.com/Tfarcenim/Daves-Potioneering/files/14079803/latest.log)
[crash-2024-01-31_13.51.39-server.txt](https://github.com/Tfarcenim/Daves-Potioneering/files/14107720/crash-2024-01-31_13.51.39-server.txt)
[latest.log](https://github.com/Tfarcenim/Daves-Potioneering/files/14107721/latest.log)

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1-11
