### ISSUE TITLE
[Forge 1.19.2] Crash on JEI

### ISSUE THREAD

**Issue by ffuentesm** [Tfarcenim/Daves-Potioneering#7]
The problem is with the Gekolib item animation render. Something similar happened last week with Ars Nouveau.
Dave's Potioneering 1.19.2-1.0.1 - may have caused crash
Just Enough Items 11.4.0.274 - may have caused crash
GeckoLib 3.1.32
![image](https://user-images.githubusercontent.com/44974827/199060296-c6a088f3-66ee-47f8-8c89-876f74add97c.png)
https://crashy.net/S8lmPbR7WF0M5cpXMOs6

**Comment by Tfarcenim** [comment]
Update Geckolib to 3.1.34, they made some breaking changes, the next version will enforce this requirement.
