### ISSUE TITLE
Incompatibility with Legendary Tooltips

### ISSUE THREAD

**Issue by Zifiv** [Tfarcenim/Daves-Potioneering#8]
Hello,

Dave's Potioneering seems to be nice, but unfortunately it seems to break an another basic mod (but that is so cool) [Legendary Tooltips (Fabric)](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips-fabric).

I do not know why, but with Dave's Potioneering installed, the outlines of tooltips is just... black or totaly removed like the image below :
![image](https://user-images.githubusercontent.com/833854/201998609-3e764db4-8c57-43bd-8df1-83fbb5333321.png)

It's very strange because if I'm in the search tab in Creative mode the issue is done and everything works well :
![image](https://user-images.githubusercontent.com/833854/201999207-0c49609c-10d8-41ff-a47f-3ef73b141804.png)

**Comment by Zifiv** [comment]
Hello @Tfarcenim, why did you close the issue ?
You found a fix or you won't fix it ?

**Comment by Tfarcenim** [comment]
it was fixed
